### ISSUE TITLE
Add support for HTML and RichText (RTF) clipboard sections

### ISSUE THREAD

**Issue by JamesMGreene** [zeroclipboard/zeroclipboard#143]
**Tasks:**
- [ ] Add a `setHtml` method to the `ZeroClipboard` JS client instances
- [ ] Add a `setRichText` method to the `ZeroClipboard` JS client instances
- [ ] Add support for `setHtml` on the Flash side
- [ ] Add support for `setRichText` on the Flash side
- [ ] Disable support for HTML/RichText by default when running on Linux
- [ ] Add an option for consumers to override and re-enable HTML/RichText support on Linux despite its known limitations

**Optional Tasks:**
- [ ] Provide an `htmlToRtf` method in a demo or docs (_not_ in the ZeroClipboard library itself)

**Related:**
- Design discussion: #22
- Linux problems: #78
